name: flecs
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.0.0-218.0.dev <4.0.0'

dependencies:
  collection: ^1.17.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
