name: CI

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: dev

      - name: Install dependencies
        run: cd packages/flecs & dart pub get

      #- name: Verify formatting
      #  run: dart --enable-experiment=records format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: dart --enable-experiment=records analyze

      - name: Test
        run: dart --enable-experiment=records test